App/config/routes.rb
Rails.application.routes.draw do
  resources :team_members
  resources :members
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

App/app/models/member.rb
class Member < ApplicationRecord
	has_many :teammember
	has_many :team, through: :teammember
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

App/app/models/team.rb
class Team < ApplicationRecord
	has_many :teammember
	has_many :member, through: :teammember
end

App/app/models/team_member.rb
class TeamMember < ApplicationRecord
	belongs_to :team
	belongs_to :member

	validate do
		new_team = Team.find(self.team_id)
		new_color = new_team.color
		member = Member.find(self.member_id)
		TeamMember.where(member_id: self.member_id).each do |mt|
			team = Team.find(mt.team_id)
			if team.color == new_color
				errors.add(:team, "Error")
			end
		end 
	end
end

App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

App/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

App/app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:team_id, :member_id)
    end
end

App/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :color)
    end
end

App/app/helpers/application_helper.rb
module ApplicationHelper
end

App/app/helpers/members_helper.rb
module MembersHelper
end

App/app/helpers/team_members_helper.rb
module TeamMembersHelper
end

App/app/helpers/teams_helper.rb
module TeamsHelper
end

App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

App/app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

App/app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

App/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

App/app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

App/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

App/app/views/team_members/_form.html.erb
<%= form_with(model: team_member, local: true) do |form| %>
  <% if team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% team_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.number_field :member_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

App/app/views/team_members/edit.html.erb
<h1>Editing Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

App/app/views/team_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Members</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.team_id %></td>
        <td><%= team_member.member_id %></td>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Member', new_team_member_path %>

App/app/views/team_members/new.html.erb
<h1>New Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Back', team_members_path %>

App/app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_member.team_id %>
</p>

<p>
  <strong>Member:</strong>
  <%= @team_member.member_id %>
</p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>